local-simulation:
  user-workflow:
    workflow-name: "cresolver-resolution-local"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.json"
    secrets-path: "../secrets.yaml"

staging-settings:
  user-workflow:
    workflow-name: "cresolver-resolution-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.json"
    secrets-path: "../secrets.yaml"

# Backward-compatible alias for previous target naming used in this repo.
staging:
  user-workflow:
    workflow-name: "cresolver-resolution-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.json"
    secrets-path: "../secrets.yaml"
