local-simulation:
  user-workflow:
    workflow-name: "cresolver-resolution-local"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.json"
    secrets-path: "../secrets.yaml"

staging-settings:
  user-workflow:
    workflow-name: "cresolver-resolution-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: "../secrets.yaml"
  
production-settings:
  user-workflow:
    workflow-name: "cresolver-resolution-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./production.config.json"
    secrets-path: "../secrets.yaml"
