local-simulation:
  user-workflow:
    workflow-name: "cresolver-resolution-local"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./local.config.json"
    secrets-path: "../secrets.yaml"

staging-settings:
  user-workflow:
    workflow-name: "cresolver-resolution-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: "../secrets.yaml"

sepolia-mock:
  user-workflow:
    workflow-name: "cresolver-resolution-sepolia-mock"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.sepolia-mock.json"
    secrets-path: "../secrets.yaml"

production-settings:
  user-workflow:
    workflow-name: "cresolver-resolution-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: "../secrets.yaml"
