# CRE project settings (CLI v1.x):
# targets are declared at root level.

local-simulation:
  rpcs:
    - chain-name: anvil-devnet
      url: "http://127.0.0.1:8547"
  experimental-chains:
    - chain-selector: 31337
      rpc-url: "http://127.0.0.1:8547"
      # setup-demo.ts uses the default Anvil deployer as forwarder in local/e2e.
      forwarder: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  description: "Local Anvil devnet for simulation and testing"

staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: "https://ethereum-sepolia-rpc.publicnode.com"
  description: "Sepolia testnet staging environment"
